// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjW_5uYEHc8Fs2KNjiymmpoJx8J7Y5Ys4',
    appId: '1:627727910556:web:8945bf870ff3d8d6bd0f59',
    messagingSenderId: '627727910556',
    projectId: 'livenotes-3485d',
    authDomain: 'livenotes-3485d.firebaseapp.com',
    storageBucket: 'livenotes-3485d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArUX486Zoqe-jha2vaSJTekJHES5EdM5s',
    appId: '1:627727910556:android:8e2aa6924f824fdabd0f59',
    messagingSenderId: '627727910556',
    projectId: 'livenotes-3485d',
    storageBucket: 'livenotes-3485d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPNsuX_aMFN8gHzTayhcHVs7cy3F8NgXY',
    appId: '1:627727910556:ios:4f2a8b7e186efee7bd0f59',
    messagingSenderId: '627727910556',
    projectId: 'livenotes-3485d',
    storageBucket: 'livenotes-3485d.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPNsuX_aMFN8gHzTayhcHVs7cy3F8NgXY',
    appId: '1:627727910556:ios:4f2a8b7e186efee7bd0f59',
    messagingSenderId: '627727910556',
    projectId: 'livenotes-3485d',
    storageBucket: 'livenotes-3485d.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjW_5uYEHc8Fs2KNjiymmpoJx8J7Y5Ys4',
    appId: '1:627727910556:web:b76e7252fa0280c0bd0f59',
    messagingSenderId: '627727910556',
    projectId: 'livenotes-3485d',
    authDomain: 'livenotes-3485d.firebaseapp.com',
    storageBucket: 'livenotes-3485d.firebasestorage.app',
  );
}
